name: CI/CD Pipeline

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install Frontend Dependencies
        working-directory: ./frontend
        run: |
          npm install
          npm run test

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Backend Dependencies
        working-directory: ./backend
        run: |
          pip install -r requirements.txt
          pytest

  deploy:
    name: Deploy to Hosting
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Deploy Backend
        working-directory: ./backend
        run: |
          echo "Deploying backend to hosting service..."
          # Add commands to deploy backend (e.g., SSH, AWS CLI)

      - name: Deploy Frontend
        working-directory: ./frontend
        run: |
          echo "Deploying frontend to hosting service..."
          # Add commands to deploy frontend (e.g., npm run build + upload)
